parse_config:
  preprocess: true
  skip_binding_parsing: false
  raw_binding_map: {}
  sticky_label: sticky
  toggle_label: toggle
  tap_toggle_label: tap-toggle
  trans_legend:
    t: ▽
    type: trans
  layer_legend_map: {}
  mark_alternate_layer_activators: false
  modifier_fn_map:
    left_ctrl: Ctl
    right_ctrl: Ctl
    left_shift: Sft
    right_shift: Sft
    left_alt: Alt
    right_alt: AltGr
    left_gui: Gui
    right_gui: Gui
    keycode_combiner: '{mods}+{key}'
    mod_combiner: '{mod_1}+{mod_2}'
    special_combinations:
      left_ctrl+left_alt+left_gui+left_shift: Hyper
      left_ctrl+left_alt+left_shift: Meh
  qmk_remove_keycode_prefix:
  - KC_
  qmk_keycode_map:
    XXXXXXX: ''
    'NO': ''
    MINUS: '-'
    MINS: '-'
    EQUAL: '='
    EQL: '='
    LEFT_BRACKET: '['
    LBRC: '['
    RIGHT_BRACKET: ']'
    RBRC: ']'
    BACKSLASH: \
    BSLS: \
    NONUS_HASH: '#'
    NUHS: '#'
    SEMICOLON: ;
    SCLN: ;
    QUOTE: ''''
    QUOT: ''''
    GRAVE: '`'
    GRV: '`'
    COMMA: ','
    COMM: ','
    DOT: .
    SLASH: /
    SLSH: /
    TILDE: '~'
    TILD: '~'
    EXCLAIM: '!'
    EXLM: '!'
    AT: '@'
    HASH: '#'
    DOLLAR: $
    DLR: $
    PERCENT: '%'
    PERC: '%'
    CIRCUMFLEX: ^
    CIRC: ^
    AMPERSAND: '&'
    AMPR: '&'
    ASTERISK: '*'
    ASTR: '*'
    LEFT_PAREN: (
    LPRN: (
    RIGHT_PAREN: )
    RPRN: )
    UNDERSCORE: _
    UNDS: _
    PLUS: +
    LEFT_CURLY_BRACE: '{'
    LCBR: '{'
    RIGHT_CURLY_BRACE: '}'
    RCBR: '}'
    PIPE: '|'
    COLON: ':'
    COLN: ':'
    DOUBLE_QUOTE: '"'
    DQUO: '"'
    DQT: '"'
    LEFT_ANGLE_BRACKET: <
    LABK: <
    LT: <
    RIGHT_ANGLE_BRACKET: '>'
    RABK: '>'
    GT: '>'
    QUESTION: '?'
    QUES: '?'
    KC_TAB: '$$phosphor:bold/caret-line-right$$'
    C(KC_TAB): '$$phosphor:bold/text-outdent$$'
    C(S(KC_TAB)): '$$phosphor:bold/text-indent$$'
    KC_SPC: '$$phosphor:bold/rectangle-dashed$$'
    KC_LSFT: '$$phosphor:bold/arrow-fat-line-up$$'
    KC_RSFT: '$$phosphor:bold/arrow-fat-line-up$$'
    KC_LALT: '$$phosphor:bold/optIon$$'
    KC_RALT: '$$phosphor:bold/optIon$$'
    KC_LGUI: '$$phosphor:bold/linux-logo$$'
    KC_RGUI: '$$phosphor:bold/linux-logo$$'
    KC_LCTL: '$$phosphor:bold/control$$'
    KC_RCTL: '$$phosphor:bold/control$$'
    KC_ENT: '$$phosphor:bold/key-return$$'
    KC_BSPC: '$$phosphor:bold/backspace$$'
    KC_DOWN: '$$phosphor:bold/arrow-down$$'
    KC_UP: '$$phosphor:bold/arrow-up$$'
    KC_LEFT: '$$phosphor:bold/arrow-left$$'
    KC_RIGHT: '$$phosphor:bold/arrow-right$$'
    RM_TOGG: '$$phosphor:bold/lightbulb$$'
    KC_VOLD: '$$phosphor:bold/speaker-low$$'
    KC_VOLU: '$$phosphor:bold/speaker-high$$'
    KC_MUTE: '$$phosphor:bold/speaker-slash$$'
    KC_MPRV: '$$phosphor:bold/skip-back$$'
    KC_MNXT: '$$phosphor:bold/skip-forward$$'
    KC_MSTP: '$$phosphor:bold/stop$$'
    KC_MPLY: '$$phosphor:bold/play-pause$$'
    KC_HOME: '$$phosphor:bold/caret-line-up$$'
    KC_PGUP: '$$phosphor:bold/caret-up$$'
    KC_END: '$$phosphor:bold/caret-line-down$$'
    KC_PGDN: '$$phosphor:bold/caret-down$$'
